;; Exercise 1.14
;; Drawing the tree illustrating the  process generated by count-change
;; What are the orders of the space and number of steps used by this
;; process as the amount of change increases

;; You can read more here:
;; http://eli.thegreenplace.net/2007/06/28/sicp-section-123
